{{- if not .Values.mongodb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librechat-exporter.fullname" . }}
  labels:
    {{- include "librechat-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-uri: {{ required "mongodb.uri is required when mongodb.existingSecret is not set" .Values.mongodb.uri | quote }}
{{- end }}
