{
 "title": "eval over time",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "messages|tokens per user",
   "type": "timeseries",
   "description": "messages | tokens on a day, divided by users on a day",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT \n    m.date,\n    m.total_messages / u.unique_users as messages_per_user,\n    SUM(t.input_tokens + t.output_tokens) / u.unique_users as tokens_per_user\nFROM daily_messages m\nJOIN daily_users u ON m.date = u.date\nJOIN daily_tokens_by_model t ON m.date = t.date\nGROUP BY m.date, m.total_messages, u.unique_users\nORDER BY m.date"
    }
   ]
  },
  {
   "title": "models | error count",
   "type": "barchart",
   "description": "model error count",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT \n    date as time,\n    model,\n    error_count\nFROM daily_errors_by_model\nWHERE $__timeFilter(date)\nORDER BY time"
    }
   ]
  },
  {
   "title": "user token podium",
   "type": "barchart",
   "description": "5 users with top token usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT\n    user,\n    SUM(input_tokens) AS input_tokens,\n    SUM(output_tokens) AS output_tokens,\n    SUM(input_tokens + output_tokens) AS total_tokens\nFROM daily_tokens_by_user\nWHERE $__timeFilter(date)\nGROUP BY user\nORDER BY total_tokens DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "user token usage",
   "type": "timeseries",
   "description": "5 users with top token usage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT \n    date as time,\n    user,\n    input_tokens + output_tokens\nFROM daily_tokens_by_user\nWHERE $__timeFilter(date)\nORDER BY time"
    }
   ]
  },
  {
   "title": "all model token usage",
   "type": "timeseries",
   "description": "adds input and output tokens of all models used",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT \n    date as time,\n    SUM(input_tokens + output_tokens) AS total_tokens\nFROM daily_tokens_by_model\nWHERE $__timeFilter(date)\nGROUP BY date\nORDER BY time"
    }
   ]
  },
  {
   "title": "models | input token",
   "type": "timeseries",
   "description": "model token input",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT \n    date as time,\n    model,\n    input_tokens\nFROM daily_tokens_by_model\nWHERE $__timeFilter(date)\nORDER BY time"
    }
   ]
  },
  {
   "title": "models | output token",
   "type": "timeseries",
   "description": "model token output",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT \n    date as time,\n    model,\n    output_tokens\nFROM daily_tokens_by_model\nWHERE $__timeFilter(date)\nORDER BY time"
    }
   ]
  },
  {
   "title": "daily unique users",
   "type": "timeseries",
   "description": "a user who has had at least one conversation on a day",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT date, unique_users FROM metrics.daily_users"
    }
   ]
  },
  {
   "title": "weekly unique users",
   "type": "timeseries",
   "description": "a user who has had at least one conversation on a week",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT unique_users, week_start FROM metrics.weekly_users"
    }
   ]
  },
  {
   "title": "monthly unique users",
   "type": "timeseries",
   "description": "a user who has had at least one conversation on a month",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "dataset": "metrics",
     "rawSql": "SELECT unique_users, month_start FROM metrics.monthly_users"
    }
   ]
  }
 ]
}